/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visualnovel;

/**
 *
 * @author Estevan
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonEditor = new javax.swing.JButton();
        ButtonGame = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(423, 297));
        getContentPane().setLayout(new java.awt.GridLayout());

        ButtonEditor.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ButtonEditor.setText("Editor");
        ButtonEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditorActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonEditor);

        ButtonGame.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        ButtonGame.setText("Game");
        ButtonGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonGameActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonGame);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditorActionPerformed
        Editor e = new Editor();
        e.main(null);
        dispose();
    }//GEN-LAST:event_ButtonEditorActionPerformed

    private void ButtonGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonGameActionPerformed
        Game g = new Game();
        g.main(null);
        dispose();
    }//GEN-LAST:event_ButtonGameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEditor;
    private javax.swing.JButton ButtonGame;
    // End of variables declaration//GEN-END:variables
}
